-- app.data

CREATE USER app_data IDENTIFIED BY "23W5yJ4D9qe3y8F"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_ocde
CREATE USER app_code IDENTIFIED BY "ERPaDiXd9U4sXhm"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_admin
CREATE USER app_admin IDENTIFIED BY "sVhfoiPehveEXJv1"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

--app_user 
CREATE USER app_user IDENTIFIED BY "hRkX0AYWSwmqbLg"
ENABLE EDITIONS;